# Change these first
owner: peburke # Your GitHub organization or username, where this repository lives
repo: myuptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: MyPlace
    url: http://camera.flyfpv.ca:3888

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /myuptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: GUSTAVE
  introTitle: "**Pete's** Internet access monitor."
  introMessage: GUSTAVE Status Page
  navbar:
    - title: My Status
      href: https://www.facebook.com/burke.peter
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
